# Generated by Django 4.2.7 on 2024-01-14 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vuz_1',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название ВУЗа')),
                ('short_name', models.CharField(max_length=255, verbose_name='Короткое название ВУЗа')),
                ('url', models.CharField(max_length=255, verbose_name='Сайт ВУЗа')),
                ('logo', models.ImageField(upload_to='вузы/', verbose_name='Логотип')),
                ('obr_pr', models.IntegerField(verbose_name='Образовательных программ')),
                ('pr_b', models.IntegerField(verbose_name='Минимальный проходной балл')),
                ('bm', models.IntegerField(verbose_name='Бюджетных мест')),
                ('adress', models.CharField(default='', max_length=255, verbose_name='Адрес')),
                ('coordinates', models.CharField(default='', max_length=255, verbose_name='Координаты')),
                ('latitude', models.CharField(default='', max_length=255, verbose_name='Широта')),
                ('longitude', models.CharField(default='', max_length=255, verbose_name='Долгота')),
                ('metro_name', models.CharField(default='', max_length=255, verbose_name='Название станции метро')),
                ('metro_latitude', models.CharField(default='', max_length=255, verbose_name='Широта метро')),
                ('metro_longitude', models.CharField(default='', max_length=255, verbose_name='Долгота метро')),
                ('name_metro', models.CharField(default='', max_length=255, verbose_name='Название станции метро')),
                ('distance_to_metro', models.FloatField(default='', verbose_name='Расстояние от главного корпуса до метро')),
            ],
            options={
                'verbose_name_plural': 'Вузы',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=5000, verbose_name='Текст отзыва')),
                ('rait', models.FloatField(default='', verbose_name='Оценка')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vuz_1', verbose_name='Название ВУЗа')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
