# Generated by Django 4.2.7 on 2024-01-14 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments_1',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000, verbose_name='Текст отзыва')),
                ('rait', models.FloatField(verbose_name='Оценка')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оставления')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vuz_1', verbose_name='Название ВУЗа')),
            ],
        ),
    ]
