# Generated by Django 4.2.7 on 2024-01-14 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comments_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments_2',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_1', models.TextField(max_length=5000, verbose_name='Учеба')),
                ('rait_1', models.FloatField(verbose_name='Оценка_учеба')),
                ('text_2', models.TextField(max_length=5000, verbose_name='Преподаватели')),
                ('rait_2', models.FloatField(verbose_name='Оценка_преподаватели')),
                ('text_3', models.TextField(max_length=5000, verbose_name='Студенческая жизнь')),
                ('rait_3', models.FloatField(verbose_name='Оценка_студенческая жизнь')),
                ('text_4', models.TextField(max_length=5000, verbose_name='Расположение')),
                ('rait_4', models.FloatField(verbose_name='Оценка_расположение')),
                ('text_5', models.TextField(max_length=5000, verbose_name='Общежитие')),
                ('rait_6', models.FloatField(verbose_name='Оценка_общежитие')),
                ('rait', models.FloatField(verbose_name='Оценка_общая')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата оставления')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vuz_1', verbose_name='Название ВУЗа')),
            ],
        ),
    ]
