# Generated by Django 4.2.7 on 2024-01-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_comments_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_2',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
