# Generated by Django 4.2.7 on 2024-01-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_comments_2_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_2',
            name='rait',
            field=models.IntegerField(verbose_name='Оценка_общая'),
        ),
        migrations.AlterField(
            model_name='comments_2',
            name='rait_1',
            field=models.IntegerField(verbose_name='Оценка_учеба'),
        ),
        migrations.AlterField(
            model_name='comments_2',
            name='rait_2',
            field=models.IntegerField(verbose_name='Оценка_преподаватели'),
        ),
        migrations.AlterField(
            model_name='comments_2',
            name='rait_3',
            field=models.IntegerField(verbose_name='Оценка_студенческая жизнь'),
        ),
        migrations.AlterField(
            model_name='comments_2',
            name='rait_4',
            field=models.IntegerField(verbose_name='Оценка_расположение'),
        ),
        migrations.AlterField(
            model_name='comments_2',
            name='rait_6',
            field=models.IntegerField(verbose_name='Оценка_общежитие'),
        ),
    ]
