# Generated by Django 4.2.7 on 2024-01-14 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_comments_2_rait_alter_comments_2_rait_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.TextField(max_length=250, verbose_name='Текст отзыва')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vuz_1', verbose_name='Название ВУЗа')),
            ],
        ),
    ]
