# Generated by Django 4.2.7 on 2024-01-15 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuz_1',
            name='distance_between_buildings',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.TextField(max_length=250, verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
