# Generated by Django 4.2.7 on 2024-01-15 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_vuz_1_distance_between_buildings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('programm', models.TextField(max_length=250, verbose_name='Направление подготовки программы')),
                ('passing_score', models.IntegerField(blank=True, null=True, verbose_name='Проходной балл на очное в 2023 году')),
                ('budget_places', models.IntegerField(blank=True, null=True, verbose_name='Бюджетных мест на очное в 2024 году')),
                ('cost_of_education', models.IntegerField(blank=True, null=True, verbose_name='Стоимость обучения очное')),
                ('сod_programm', models.TextField(max_length=250, verbose_name='Код программы')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vuz_1', verbose_name='Название ВУЗа')),
            ],
        ),
    ]
