# Generated by Django 4.2.7 on 2024-01-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_programms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_2',
            name='text_1',
            field=models.TextField(default='', max_length=5000, verbose_name='Учеба'),
        ),
        migrations.AlterField(
            model_name='comments_2',
            name='text_2',
            field=models.TextField(default='', max_length=5000, verbose_name='Преподаватели'),
        ),
        migrations.AlterField(
            model_name='comments_2',
            name='text_3',
            field=models.TextField(default='', max_length=5000, verbose_name='Студенческая жизнь'),
        ),
        migrations.AlterField(
            model_name='comments_2',
            name='text_4',
            field=models.TextField(default='', max_length=5000, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='comments_2',
            name='text_5',
            field=models.TextField(default='', max_length=5000, verbose_name='Общежитие'),
        ),
    ]
