# Generated by Django 4.2.7 on 2024-01-15 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_comments_2_text_1_alter_comments_2_text_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_2',
            name='text_1',
            field=models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Учеба'),
        ),
        migrations.AlterField(
            model_name='comments_2',
            name='text_2',
            field=models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Преподаватели'),
        ),
        migrations.AlterField(
            model_name='comments_2',
            name='text_3',
            field=models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Студенческая жизнь'),
        ),
        migrations.AlterField(
            model_name='comments_2',
            name='text_4',
            field=models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='comments_2',
            name='text_5',
            field=models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Общежитие'),
        ),
    ]
