# Generated by Django 4.2.7 on 2024-01-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_comments_2_text_1_alter_comments_2_text_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuz_1',
            name='distance_from_dormitory',
            field=models.FloatField(blank=True, null=True, verbose_name='Расстояние до общежития от гл корп'),
        ),
    ]
